### ISSUE TITLE
Custom colours?

### ISSUE THREAD

**Issue by PaulWalkerUK** [OllieTerrance/Homely#10]
Is there a way I can set custom colours for buttons, using for example RGB values? Is there anything I can add to Custom CSS to create my own Styles perhaps, or if not, can I override the existing ones?

**Comment by OllieTerrance** [comment]
You can use a Bootstrap button CSS generator like [this one](http://twitterbootstrap3buttons.w3masters.nl) to make a custom colour, add the resulting code to Homely's custom CSS field, then use the wand button in the list of button styles to specify a class name.

(The linked generator uses "custom" as the class name -- you'll need to replace that with something else when adding multiple options.)

**Comment by Droyk** [comment]
Not working!!

This is what the above-linked generator provided me 

`.btn-custom {
  background-color: #D139BD;
  border-color: #D139BD;
}
.btn-custom:hover,
.btn-custom:focus,
.btn-custom:active,
.btn-custom.active {
  background-color: #c32daf;
  border-color: #ae299d;
}
.btn-custom.disabled:hover,
.btn-custom.disabled:focus,
.btn-custom.disabled:active,
.btn-custom.disabled.active,
.btn-custom[disabled]:hover,
.btn-custom[disabled]:focus,
.btn-custom[disabled]:active,
.btn-custom[disabled].active,
fieldset[disabled] .btn-custom:hover,
fieldset[disabled] .btn-custom:focus,
fieldset[disabled] .btn-custom:active,
fieldset[disabled] .btn-custom.active {
  background-color: #D139BD;
  border-color: #D139BD;
}`

I pasted the above into the Homely's custom CSS field than I added `custom` as a class name It didn't work it gave me a default grey colour then I added `btn-custom` as a class name. it only worked in a preview, but after hitting save it gave me black background & blue text, which you can see below.

![Annotation 2019-04-30 130045](https://user-images.githubusercontent.com/15848350/56946582-196e7f00-6b48-11e9-94db-786d0560c989.jpg)
![Annotation 2019-04-30 124927](https://user-images.githubusercontent.com/15848350/56946585-1a071580-6b48-11e9-89f4-0ed68706a4a4.png)
![Annotation 2019-04-30 125939](https://user-images.githubusercontent.com/15848350/56946583-196e7f00-6b48-11e9-8a6c-6ef298ac5973.jpg)

**Comment by Terrance** [comment]
You need to enter `custom` rather than `btn-custom` in the class prompt.

**Comment by Droyk** [comment]
**It worked.** it's weird I tried that before it didn't work or I never tried to save it coz I saw the grey preview. 
![Annotation 2019-04-30 163411](https://user-images.githubusercontent.com/15848350/56957916-50ec2400-6b66-11e9-9d2d-ffcda5e53252.png)

but if I add `btn-custom` as my class name it shows correct colour preview as soon as I hit `ok` I wonder why is that though?

**Comment by Droyk** [comment]
also, Is it possible to not change the colour of the text while hovering?

normal button 
![Annotation 2019-04-30 163411](https://user-images.githubusercontent.com/15848350/56986574-b52fd780-6ba8-11e9-97eb-a07d4f1c7cb7.png)

if a user hover over it
![Annotation 2019-04-30 163412](https://user-images.githubusercontent.com/15848350/56986579-b6f99b00-6ba8-11e9-8818-41ef1f5cc177.png)

**Comment by Droyk** [comment]
@Terrance is there is any way to not to change the text colour while hovering over the link button

normal button 
![Annotation 2019-04-30 163411](https://user-images.githubusercontent.com/15848350/56986574-b52fd780-6ba8-11e9-97eb-a07d4f1c7cb7.png)

if a user hover over it
![Annotation 2019-04-30 163412](https://user-images.githubusercontent.com/15848350/56986579-b6f99b00-6ba8-11e9-8818-41ef1f5cc177.png)

**Comment by Droyk** [comment]
Don't worry about it. it seems I just needed to add `color: #fff;` in the code to get the desired effect. it seems fine now.

**Comment by iDeeLaw** [comment]
> Don't worry about it. it seems I just needed to add `color: #fff;` in the code to get the desired effect. it seems fine now.

Mind posting what it looks like when you added the "color: #fff;" ? Ty! @Droyk
