### ISSUE TITLE
Not searching/finding bookmarks folder, only sites.

### ISSUE THREAD

**Issue by MartinLichtblau** [OllieTerrance/Homely#5]
s.T.

**Comment by OllieTerrance** [comment]
The search box on the bookmarks widget just searches bookmarks.  You can search through all your links from the omnibox (type `hl` and press tab).

Both have substring matching, so for example, you can find "YouTube" with `tube` but not `yt`.

Is that what you're asking for?

**Comment by MartinLichtblau** [comment]
No, not really. I wanted to find a bookmarks folder with the search (Inside homely, or omnibox), but it looks it just shows bookmark links as results, but not bookmarks folders. 
Which is very helpful, if you can search a bookmarks folder (e.g. morning news), and it open all sites (e.g. news provider) contained in the folder . But ok, I got my answers - feature not available. 
Still, thank you for your open source coding. Cya!

**Comment by OllieTerrance** [comment]
Ahh, including folders of bookmarks in the bookmark search.  Gotcha.

Indeed, not possible at the moment.  I just had a quick go at implementing this, but I think most of the bookmark code will need some refactoring (there's some awkward dependencies between the helper methods and the bookmark tree returned by Chrome).  I'll see what can be done.

**Comment by MartinLichtblau** [comment]
In this area Chrome is really messy. Perhaps you can still find a way through. 
I once used such a feature and I was a great productivity helper, since I have lots of bookmarks, but all very structured, I could easily access all my projects, news collections, Watch lists, and such things. 
Image for yourself, how such a feature could help you, and so decide whether it's worth the effort ;)

**Comment by OllieTerrance** [comment]
Refactoring has occurred -- git version now includes folders in search results!  😃

**Comment by MartinLichtblau** [comment]
Wow, that's intense! 
Tried it and the search bar on the homely page works - it shows the folder and opens all sites inside! Yeah :) So it looks good. Just the omnibox isn't returning any results, don't know why. 
That some lines of code you wrote there. Incredible!

**Comment by OllieTerrance** [comment]
Omnibox search should still be working, though that won't return bookmarks (since Chrome suggests them natively), only pages in the links section?

![image](https://cloud.githubusercontent.com/assets/4025899/17418821/5a09343e-5a92-11e6-8085-6fb4af20dfc4.png)
(e.g. links under a _Settings_ menu in the _Chrome_ block)

**Comment by MartinLichtblau** [comment]
Ahh, ok. that still works! I first thought the homely page and the omnibox use the same search algorithm. 
Thanks for the explanation.

**Comment by OllieTerrance** [comment]
Indeed, search box on the bookmarks widget only searches them, and omnibox only searches links.  Not really a clean way to show both together, but most of the time I only need to search links...
