### ISSUE TITLE
I add a local html file to the Links, But it doesnot work

### ISSUE THREAD

**Issue by neatgz** [OllieTerrance/Homely#8]
I add webui-aria2 to Homely's links, the format like this:
file:///C:/Apps/Green/aria2/webui-aria2/index.html
but It doesnot work.
and It works well if I add the link to the bookmarks.

**Comment by OllieTerrance** [comment]
> Not allowed to load local resource: file:///C:/

Looks like a Chrome limitation, but can probably be worked around in the same way as `chrome://` URLs.
